version: 2
updates:
  # Maintain dependencies for backend
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "main"
    groups:
      main-dependencies:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps):"

  # Maintain dependencies for frontend
  - package-ecosystem: "npm"
    directory: "frontend/"
    target-branch: "main"
    versioning-strategy: increase-if-necessary
    commit-message:
      prefix: "chore(deps):"
    groups:
      main-dependencies:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
    schedule:
      interval: "weekly"
